---
- name: tomcat
  hosts: all
  become: yes 
  tasks:
    - name: Install java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: true
        state: present
    - name: create a tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: create a tomcat user
      ansible.builtin.user:
        name: tomcat
        create_home: true
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: present
    - name: unarchive the file
      ansible.builtin.unarchive:
         src: https://www-eu.apache.org/dist/tomcat/tomcat-10/v10.1.6/bin/apache-tomcat-10.1.6.tar.gz
         dest: /opt/tomcat
         remote_src: yes
    - name: Create a symbolic link
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-10.1.6
        dest: /opt/tomcat/latest
        state: link
    - name: Giving recurive permission
      ansible.builtin.file:
        dest: /opt/tomcat
        owner: tomcat
        group: tomcat
        state: directory
    - name: add execute permissions to shell files
      ansible.builtin.command: sudo sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'
    - name: copy file from local system
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
        owner: tomcat
        group: tomcat
    - name: systemctl reload
      ansible.builtin.systemd :
        name: tomcat.service
        daemon_reload: yes
        enabled: yes
        state: started

    
        
    
